# Generated by Django 4.2.7 on 2023-12-28 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                18, message="Coach can't be younger than 18"
                            ),
                            django.core.validators.MaxValueValidator(
                                90, message="Coach can't be older than 90"
                            ),
                        ]
                    ),
                ),
                ("nationality", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "coaches",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1700, message="Year must be 1700 or greater."
                            ),
                            django.core.validators.MaxValueValidator(
                                2023, message="Year cannot be in the future."
                            ),
                        ]
                    ),
                ),
                (
                    "coach",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club",
                        to="football.coach",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "city")},
            },
        ),
    ]
