# Generated by Django 4.2.7 on 2023-12-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="coach",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club",
                to="football.coach",
            ),
        ),
    ]
